package workshop.projecteuler

/**
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * Created by hoppel on 28.01.15.
 */
object Problem2 {

  def problem2(maximum: Int) : Long = {
    lazy val fibs: Stream[Long] = 0 #:: 1 #:: fibs.zip(fibs.tail).map(x => x._1 + x._2)
    fibs.takeWhile(x => x < maximum).filter( x => x%2 == 0).sum
  }
}
